version: '3'
services:
  app:
    container_name: docker-pollerize
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - docker-mysql
  mongo:
    container_name: docker-mysql
    image: mysql:5.7
    ports:
      - '3307:3306'