version: '3'
services:
  app:
    container_name: docker-pollerize
    restart: always
    build: .
    ports:
      - '8085:3000'
    links:
      - mysql
  mysql:
    container_name: docker-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=pollerize
    ports:
      - '3307:3306'